# Generated by Django 4.2 on 2023-05-16 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_reaction_tweet_replyreaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='tweet',
            options={'verbose_name': 'Твит', 'verbose_name_plural': 'Твиты'},
        ),
        migrations.AlterField(
            model_name='reaction',
            name='tweet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.tweet'),
        ),
    ]
