# Generated by Django 4.2 on 2023-05-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='short_info',
            new_name='short_info',
        ),
    ]
